export const AUTH_START = 'AUTH_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const FETCH_CREATED_EVENTS_START = "FETCH_CREATED_EVENTS_START";
export const FETCH_CREATED_EVENTS_SUCCESS = "FETCH_CREATED_EVENTS_SUCCESS";
export const FETCH_CREATED_EVENTS_FAIL = "FETCH_CREATED_EVENTS_FAIL";

export const FETCH_USER_EVENTS_START = "FETCH_USER_EVENTS_START";
export const FETCH_USER_EVENTS_SUCCESS = "FETCH_USER_EVENTS_SUCCESS";
export const FETCH_USER_EVENTS_FAIL = "FETCH_USER_EVENTS_FAIL";

export const FETCH_SINGLE_EVENT_START = "FETCH_SINGLE_EVENT_START";
export const FETCH_SINGLE_EVENT_SUCCESS = "FETCH_SINGLE_EVENT_SUCCESS";
export const FETCH_SINGLE_EVENT_FAIL = "FETCH_SINGLE_EVENT_FAIL";

export const CREATE_EVENT_INIT = "CREATE_EVENT_INIT";
export const CREATE_EVENT_START = "CREATE_EVENT_START";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const ADD_INGREDEINTS_TO_EVENT_START = "ADD_INGREDEINTS_TO_EVENT_START";
export const ADD_INGREDEINTS_TO_EVENT_SUCCESS = "ADD_INGREDEINTS_TO_EVENT_SUCCESS";
export const ADD_INGREDEINTS_TO_EVENT_FAIL = "ADD_INGREDEINTS_TO_EVENT_FAIL";
