export const AUTH_START = 'AUTH_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const FETCH_CREATED_EVENTS_START = "FETCH_CREATED_EVENTS_START";
export const FETCH_CREATED_EVENTS_SUCCESS = "FETCH_CREATED_EVENTS_SUCCESS";
export const FETCH_CREATED_EVENTS_FAIL = "FETCH_CREATED_EVENTS_FAIL";

export const FETCH_USER_EVENTS_START = "FETCH_USER_EVENTS_START";
export const FETCH_USER_EVENTS_SUCCESS = "FETCH_USER_EVENTS_SUCCESS";
export const FETCH_USER_EVENTS_FAIL = "FETCH_USER_EVENTS_FAIL";

export const SINGLE_EVENT_RESET = "SINGLE_EVENT_RESET";

export const FETCH_SINGLE_EVENT_START = "FETCH_SINGLE_EVENT_START";
export const FETCH_SINGLE_EVENT_SUCCESS = "FETCH_SINGLE_EVENT_SUCCESS";
export const FETCH_SINGLE_EVENT_FAIL = "FETCH_SINGLE_EVENT_FAIL";

export const CREATE_EVENT_INIT = "CREATE_EVENT_INIT";
export const CREATE_EVENT_START = "CREATE_EVENT_START";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const CREATE_EVENT_RESET = "CREATE_EVENT_RESET";
export const UPDATE_CHOICE_RESET = "UPDATE_USER_CHOICE_RESET";

export const UPDATE_EVENT_INIT = "UPDATE_EVENT_INIT";
export const UPDATE_EVENT_START = "UPDATE_EVENT_START";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAIL = "UPDATE_EVENT_FAIL";

export const EDIT_EVENT_INIT = "EDIT_EVENT_INIT";
export const EDIT_EVENT_START = "EDIT_EVENT_START";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const EDIT_EVENT_FAIL = "EDIT_EVENT_FAIL";

export const ADD_INGREDEINTS_TO_EVENT_START = "ADD_INGREDEINTS_TO_EVENT_START";
export const ADD_INGREDEINTS_TO_EVENT_SUCCESS = "ADD_INGREDEINTS_TO_EVENT_SUCCESS";
export const ADD_INGREDEINTS_TO_EVENT_FAIL = "ADD_INGREDEINTS_TO_EVENT_FAIL";

export const UPDATE_USER_CHOICE_IN_EVENT_INIT = "UPDATE_USER_CHOICE_IN_EVENT_INIT";
export const UPDATE_USER_CHOICE_IN_EVENT_START = "UPDATE_USER_CHOICE_IN_EVENT_START";
export const UPDATE_USER_CHOICE_IN_EVENT_SUCCESS = "UPDATE_USER_CHOICE_IN_EVENT_SUCCESS";
export const UPDATE_USER_CHOICE_IN_EVENT_FAIL = "UPDATE_USER_CHOICE_IN_EVENT_FAIL";

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const ADD_USER_CHOICES_START = "ADD_USER_CHOICES";
export const ADD_USER_CHOICES_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_CHOICES_FAIL = "ADD_USER_FAIL";

export const PUBSLISH_EVENT_START = "PUBSLISH_EVENT_START";
export const PUBSLISH_EVENT_SUCCESS = "PUBSLISH_EVENT_SUCCESS";
export const PUBSLISH_EVENT_FAIL = "PUBSLISH_EVENT_FAIL";


export const ADD_USER_TO_EVENT_START = "ADD_USER_TO_EVENT_START";
export const ADD_USER_TO_EVENT_SUCCESS = "ADD_USER_TO_EVENT_SUCCESS";
export const ADD_USER_TO_EVENT_FAIL = "ADD_USER_TO_EVENT_FAIL";
